name: Build devbox-runtime-frameworks

on:
  push:
    branches: [main]
    paths:
      - "devbox-runtime/frameworks/**"
  workflow_dispatch:
    inputs:
      push_image:
        description: "Push image"
        required: false
        type: boolean
        default: true

env:
  REGISTRY: ghcr.io
  OWNER: vlee0203
  SEALOS_VERSION: "5.0.1"

jobs:
  build:
    name: Build devbox-runtime-frameworks
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate image tag
        id: tag
        run: echo "tag=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Install sealos ${{ env.SEALOS_VERSION }}
        run: |
          curl -sL https://github.com/labring/sealos/releases/download/v${{ env.SEALOS_VERSION }}/sealos_${{ env.SEALOS_VERSION }}_linux_amd64.tar.gz | sudo tar -xz -C /usr/bin sealos
          sealos version

      - name: Sealos login to ghcr.io
        run: |
          sudo sealos login -u ${{ github.repository_owner }} -p ${{ secrets.GH_PAT }} ghcr.io

      - name: Build and push frameworks (amd64)
        working-directory: devbox-runtime/frameworks/deploy
        run: |
          TAG=${{ steps.tag.outputs.tag }}
          IMAGE=${{ env.REGISTRY }}/${{ env.OWNER }}/sealos-cloud-images/devbox-runtime-frameworks
          sudo sealos build -t ${IMAGE}:${TAG} --platform linux/amd64 -f Kubefile .
          sudo rm -rf registry
          PUSH=${{ github.event_name == 'push' || inputs.push_image == true }}

          if [ "$PUSH" = "true" ]; then
            sudo sealos push ${IMAGE}:${TAG}
            sudo sealos tag ${IMAGE}:${TAG} ${IMAGE}:latest
            sudo sealos push ${IMAGE}:latest

            echo "${IMAGE}:${TAG} push success"
            echo "${IMAGE}:latest push success"
          fi
