name: Build devbox-runtime-operating-systems

on:
  workflow_dispatch:
    inputs:
      push_image:
        description: "Push image"
        required: false
        type: boolean
        default: true

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  OWNER: vlee0203
  SEALOS_VERSION: "5.0.1"

jobs:
  build:
    name: Build devbox-runtime-operating-systems
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate image tag
        id: tag
        run: echo "tag=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Install sealos ${{ env.SEALOS_VERSION }}
        run: |
          curl -sL https://github.com/labring/sealos/releases/download/v${{ env.SEALOS_VERSION }}/sealos_${{ env.SEALOS_VERSION }}_linux_amd64.tar.gz | sudo tar -xz -C /usr/bin sealos
          sealos version

      - name: Sealos login to ghcr.io
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | sudo sealos login -u ${{ github.repository_owner }} --password-stdin ghcr.io

      - name: Build and push operating-systems (amd64)
        working-directory: devbox-runtime/operating-systems/deploy
        run: |
          TAG=${{ steps.tag.outputs.tag }}
          IMAGE=${{ env.REGISTRY }}/${{ env.OWNER }}/sealos-cloud-images/devbox-runtime-operating-systems
          sudo sealos build -t ${IMAGE}:${TAG} --isolation=chroot --platform linux/amd64 -f Kubefile .
          sudo rm -rf registry
          PUSH=${{ github.event_name == 'push' || inputs.push_image == true }}

          if [ "$PUSH" = "true" ]; then
            sudo sealos push ${IMAGE}:${TAG}
            sudo sealos tag ${IMAGE}:${TAG} ${IMAGE}:latest
            sudo sealos push ${IMAGE}:latest

            echo "${IMAGE}:${TAG} push success"
            echo "${IMAGE}:latest push success"
          fi
